language: android
jdk: oraclejdk8
sudo: true

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - sys-img-armeabi-v7a-android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - add-on
  - extra
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- openssl aes-256-cbc -K $encrypted_634573b3a4f8_key -iv $encrypted_634573b3a4f8_iv
  -in signings/keystore.jks.enc -out signings/keystore.jks -d
- gem install fir-cli

before_script:
- chmod +x gradlew

script:
- "./gradlew assembleRelease"

deploy:
  provider: releases
  api_key:
    secure: R/OzMXCIDqSGJd+psZAmPtnEVsFNVWuStdqdTZh8yGPv8XeIPxs/njrMwsB5g+4j5uAMH21rc1xFClnwWCS1nHwwDQ6WcCC043aiwQFCQiLBMXNBS2YKaeGvZxshbkjyZo7vJPvXBdls3vBl/DkNFefnIQgCWjPMnZxYbD8hbqYUeprM7RUDcjafAHPedsqqvUB7Ca74RYaAVJHDxnxRTG3VF0zHG/UH3aT5NSglBl+SgCxrV+n4OXhZpBC3kqjsxBYjnMP0sLuSbDyz+i4zJ5nr6JmSBQMygN9Kvsf4bdbAaNkdsq0RqasWIM4ralU1hs2sf4VZi5/v6lD3FFUIaUuaG0JFr8DTMXkLllk5MqiQWpvntYaxlu+Tb+J9pQ6ljKkgrbomSaiNCg34e+nWhRiZBib8aGo0jLGR2wlJGJTVgGMVjss11Zx4Zm4DqvUSJM1J2OGgV10dscI7Y+zz2ANa06m+KW1q5QkCNoNbYKy3bIN2ne1RB9nUcqgo1kMZpUYQd7J6c+DaRPTSMF8QUO/2ggKyfWRjLO2tuWrlYmW7Udu7VCQsLhDOYA8E+5GxzKkquOShJIHn4X0QGZsDFNC6um6Pp4gBBsM/Aghwc2J5YDpbyt8ArycfUMG1EsjMfKdnbp7xxuctkgKk3kMaT/7uuoseZgSYoRurk/y2vqw=
  file: Sample/outputs/GroupAdapter.apk
  skip_cleanup: true
  on:
    repo: sunfusheng/GroupRecyclerViewAdapter
    tags: true
    all_branches: true

after_deploy:
- "./gradlew clean build bintrayUpload -PbintrayUser=sfsheng0322 -PbintrayKey=$BINTRAY_TOKEN -PdryRun=false"
- fir p Sample/outputs/GroupAdapter.apk -T $FIR_TOKEN -c "丰富分组列表库功能"

notifications:
  email:
  - sfsheng0322@126.com